Add taranaki well logs dataset schema
CODAIT/dax-schemata pull request #12
Opened 2020-12-10 01:04 UTC by djalova

2020-12-11 04:36 UTC, xuhdev commented
Turns out this is still blocked... Let's prioritize issues that are blocking these changes

2020-12-11 18:25 UTC, edwardleardi commented
@xuhdev Which issue is blocking this PR?

2020-12-11 19:10 UTC, xuhdev commented
@edwardleardi https://github.com/codait/pydax/issues/50 . You should be able to see if you have installed ZenHub browser extension

2020-12-15 01:49 UTC, xuhdev commented on datasets.yaml
> +              WELL_NAME: 'string'
You forgot `columns`

2020-12-16 19:08 UTC, xuhdev requested changes
Missing `columns:`

2020-12-17 00:37 UTC, xuhdev approved these changes
LGTM

2020-12-17 00:38 UTC, merged